@startuml
skinparam handwritten true
skinparam style strict

entity 利用者 {
  +会員番号: String
  --
  +氏名: String
  +種別: String
}

entity 学生 {
  --
  +学生番号: String
}

entity 教職員 {
  --
  +職員番号: String
}

entity 図書 {
  +管理番号: String
  --
  +書名: String
  +種別: String
}

entity 書籍 {
  --
  +ISBN: String
}

entity 雑誌 {
  --
  +ISSN: String
}

entity 貸出 {
  +貸出日: Date
  +返却予定日: Date
}

entity 貸出履歴 {
  +貸出日: Date
  +返却日: Date
}

entity 貸出予約 {
  +予約日: Date
}

利用者 "1" -- "0..*" 貸出: 借りる
貸出 "1" -- "1" 図書: が
利用者 "1" -- "0..*" 貸出予約: 予約する
貸出予約 "1" -- "1" 図書: を

図書 "1" -- "0..*" 貸出履歴: 記録される
利用者 "1" -- "0..*" 貸出履歴: の

利用者 <|-- 学生
利用者 <|-- 教職員
図書 <|-- 書籍
図書 <|-- 雑誌
@enduml