@startuml 大原情報科学大学・図書館システムユースケース図
left to right direction
actor 利用者 as User
actor 事務職員 as Staff
 
rectangle 大原情報科学大学・図書館システム {
  usecase "貸し出し予約" as Reserve
  usecase "貸し出し" as Checkout
  usecase "返却" as Return
  usecase "貸出履歴の閲覧" as ViewHistory
  usecase "貸出履歴の記録" as RecordHistory
  usecase "予約者への連絡" as NotifyReservation
}
 
User --|> Staff
Staff --> Checkout
Staff --> Return
Staff --> Reserve
Staff --> ViewHistory
 
Checkout ..> RecordHistory : <<include>>
Return ..> RecordHistory : <<include>>
Return ..> NotifyReservation : <<include>>
@enduml